class Error(Exception):
    pass


class UserAccessError(Exception):
    pass